# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb4b66ea3008aee69a9dd46858ae84329396e5e9d4ad899e4c0f79f8c6f459617bd1570ee0f279b6030d0f9a1122f83632f1aed87c3ccebf0e0b99a4005d1dc7

test:
  secret_key_base: 570b207ca063c1f897c56d0133d72150b23525bed7a1ee06d4f671dcec972525e0b4a2ad8110bebe9dddf62c0887dc7ff1a8092c934e93feda73cd6820b9c9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
